language: ruby
arch:
  - amd64
  - ppc64le
rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - 2.7
matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
before_install: gem install bundler --no-document
